# servic 配置 修改了配置不要忘记修改struct
[app.api]
apiName        = "wbcomic api"
apiVersion     = "1.0"

# http
apiAddr        = "127.0.0.1:8080"

# https
apiTls         = false
apiTlsAddr     = "127.0.0.1:8081"

# jwt auth
apiSecretKey   = "12345!@#$%"
apiUsername    = "demo"
apiPassword    = "pwd"

# log
apiLogFile     = ""

[app.rpc]
rpcName        = "wbcomic web service"
rpcVersion     = "1.0"

rpcAddr        = "localhost:50051"
rpcTraceAddr   = "localhost:50052"

rpcLogFile     = ""






# 数据库配置
[database.comic]
master = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]
slave = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]


[database.page]
master = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]
slave = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]


[database.wbcomic]
master = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]
slave = [
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s",
    "root:123456@tcp(127.0.0.1:3306)/solr?charset=utf8&timeout=5s"
    ]